# Beep boop let's build a page
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: [Sage the AI in Sonic 3 AIR]
description: [An upcoming Sonic 3 AIR mod by TimerBunneh and LegionTheSpiritomb]
show_downloads: [false]